FIXES ISSUE #466 Replace Sugar Stories table with HTML table
sugarlabs/www pull request #467
Opened 2024-10-12 23:42 UTC by omsuneri

Resolved png to html table.
<img width="909" alt="Screenshot 2024-10-13 at 4 56 52 AM" src="https://github.com/user-attachments/assets/445447c3-3db7-4bdf-9b48-8d929b1e7708">

2024-10-12 23:52 UTC, pikurasa commented on sugar-stories.html
> +                      <td><a href="https://wiki.sugarlabs.org/go/0.102/Notes">https://wiki.sugarlabs.org/go/0.102/Notes</a></td>
I'm certainly not an HTML expert, but I tried adding <p> and </p> around the text in these areas, and it looks better, especially on a larger screen. Please try this.

2024-10-12 23:54 UTC, pikurasa requested changes
Please try improving the HTML in the table.

A start is to add `<p></p>` to the text inside the sections of the table.

2024-10-13 19:32 UTC, pikurasa commented
After doing some research, I found that if you add `style="width: 100%; "`, then it fills the width of the screen.

`<table style="width: 100%; " class="customMargin6">`

The result looks like this:
![Screenshot from 2024-10-13 15-29-06](https://github.com/user-attachments/assets/903bc693-ade3-46f4-8397-072bad7de1ce)

Otherwise, it doesn't fill the screen's width. Right now, yours looks like this:

![Screenshot from 2024-10-13 15-31-10](https://github.com/user-attachments/assets/4e5a8ed0-4e15-4384-9df0-ce3963d7b210)

I figured this out by reading https://stackoverflow.com/questions/7138605/how-do-i-make-one-table-column-fill-all-the-spare-horizontal-space

It would also be nice if the table kept a little space around the text, whether or not the screen's width is wide or not.

2024-10-14 03:36 UTC, omsuneri commented
@pikurasa I had tried it with the width 100% but it is resulting in something more increased table than the paragraph width so it's not that much pretty and I thought with the last commit merged the paragraph width has been increased so that's why my ss is different from yours but no issues I ll update my pr according to requirements

2024-10-15 13:14 UTC, pikurasa commented
@omsuneri Is this ready for review again?

2024-10-16 18:06 UTC, merged