enhancement for service section
sugarlabs/www pull request #585
Opened 2024-12-13 09:31 UTC by Devmoni

### Description:
This PR enhances the responsiveness and styling of the service section by ensuring equal-sized boxes, centered content, and consistent spacing.

### Screenshot:

![image](https://github.com/user-attachments/assets/1c4d82dc-33a0-4c43-80e9-188335aa5093)

### Testing:
Verified changes on a local Linux-based environment.

2024-12-13 18:34 UTC, pikurasa requested changes

2024-12-13 18:34 UTC, pikurasa commented on css/airspace.css
> +  display: flex;
We're trying to put new CSS into custom.css as to not confuse future maintainers.

Please solve this in a way that doesn't change the mainstream airspace.css file.

2024-12-14 04:43 UTC, quozl commented on css/custom.css
> +}
Missing newline at end of file.

2024-12-14 04:44 UTC, quozl commented
Your commit message does not follow [our guidance](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).  In particular, you have placed in the _pull request_ opening text that would be better in the commit message.

2024-12-14 20:17 UTC, quozl commented
Thanks.  Good progress.  Please squash the commits and rewrite the commit message as mentioned.

2024-12-15 01:42 UTC, closed without merging

2024-12-15 06:17 UTC, quozl commented
Forward link; this pull request was replaced by https://github.com/sugarlabs/www/pull/592