Sugar Stories Page and Authors added
sugarlabs/www pull request #618
Opened 2024-12-29 13:51 UTC by MostlyKIGuess

Fixes #571. Continuation of #613. Special thanks to @saumyashahi for the initial work on this feature!  

### Improvements Implemented:
1. **Dynamic Author Display**  
   - To display authors on any page, simply add the `author: "Author Name"` field.  
   ![Author](https://github.com/user-attachments/assets/ac431384-ab71-44d3-99c5-82cfb30ff022)  

2. **Fallback for Missing Author Information**  
   - Since not all `_posts` include author information, an initial check has been added.  
   - If the `author` field is present, the name will be displayed. Otherwise, the layout will remain unchanged.  
   Example:  
   ![With Author](https://github.com/user-attachments/assets/488cdafd-2c6f-4d90-8d1e-4d3b963cf3c0)  
   vs  
   ![Without Author](https://github.com/user-attachments/assets/880a54e9-d794-4441-98ba-b38f15b01bf8)  

3. **Bug Fixes from #613**  
   - Resolved the issue where clicking on certain links redirected users back to the "Sugar Stories" page instead of `/press`.  
   ![Sugar Stories](https://github.com/user-attachments/assets/b76dee28-4a61-497e-be13-42890d8b0ef4)  

4. **Navigation Enhancement**  
   - Added a direct "Sugar Stories" link in the navbar for easier access.  

### Further Instructions:
1. **New Stories Addition**:New stories can be added by creating .md files in _post with the ```layout: story```.

2024-12-29 16:46 UTC, pikurasa commented
The default name, for when we do not know the name of the author, should be "Sugar Community Member".

I did not write /stories/2016/05/15/The-connection-between-Sugar-Students-Teachers/, so using my name as author for that article is misleading.

The next step would be to add:
* https://medium.com/@sugarlabs/reflections-as-a-parent-and-teacher-sugar-at-home-and-in-the-classroom-c0aa9af0e34c?source=user_profile_page---------0-------------44f32cc79724---------------
* https://medium.com/@sugarlabs/james-simmonss-sugar-story-writing-new-activities-and-sharing-sugar-with-youth-9282c66f9219?source=user_profile_page---------2-------------44f32cc79724---------------

2024-12-29 17:02 UTC, MostlyKIGuess commented
> The default name, for when we do not know the name of the author, should be "Sugar Community Member".
> 
> I did not write /stories/2016/05/15/The-connection-between-Sugar-Students-Teachers/, so using my name as author for that article is misleading.
> 
> The next step would be to add:
> * https://medium.com/@sugarlabs/reflections-as-a-parent-and-teacher-sugar-at-home-and-in-the-classroom-c0aa9af0e34c?source=user_profile_page---------0-------------44f32cc79724---------------
> * https://medium.com/@sugarlabs/james-simmonss-sugar-story-writing-new-activities-and-sharing-sugar-with-youth-9282c66f9219?source=user_profile_page---------2-------------44f32cc79724---------------

Would you happen to know who wrote that article?
And yes I will change the default behaviour.

As well as add the 2 articles as sugar stories .

2024-12-30 16:53 UTC, pikurasa commented
> Would you happen to know who wrote that article?

You can see the author for both articles in the articles -- myself for the parent one, and James Simmons for the Sugar Activity one.

2025-01-01 19:06 UTC, quozl approved these changes
Trivial changes suggested.

2025-01-01 19:06 UTC, quozl commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
Blank before tag close.

2025-01-01 19:06 UTC, quozl commented on press.html
> +                    <i class="display:block;" >By {{ post.author | default: "Sugar Community Member" }}</i>
Blank before tag close.

2025-01-01 19:06 UTC, quozl commented on _layouts/story.html
> +     </p>
Inconsistent indentation.

2025-01-02 07:23 UTC, MostlyKIGuess commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
I don't understand, what exactly do I change here?

2025-01-02 07:34 UTC, MostlyKIGuess commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
Did you mean regarding the space  `ber" }}` and the space after double quos?. It shouldn't be a problem because it only takes the String

2025-01-02 07:41 UTC, MostlyKIGuess commented on _layouts/story.html
> +     </p>
Fixed

2025-01-02 19:30 UTC, quozl commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
You changed `<i style="display: block;">` to `<<i class="display:block;" >`, but my preference is `<i class="display:block;">`, which is shorter and more expected.  When you trip your reviewer with oddness, they slow down, and if they slow down enough they say something.

2025-01-02 19:33 UTC, MostlyKIGuess commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
I am sorry I still don't understand, it's still <i for me.

2025-01-02 19:33 UTC, MostlyKIGuess commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
Oh I understood now, I will fix it and rebase

2025-01-02 19:44 UTC, quozl commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
One of our monospace font training methods 30 years ago was to play Rogue or Moria.  It taught the eye and brain to detect miniscule changes in text.  An essential skill for programming.

2025-01-02 19:47 UTC, MostlyKIGuess commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
Indeed, 🙂 I think I am having a hard time writing and testing spice and verilog code. I should adapt to the code and learn to write it as it was maintained before me.

2025-01-04 21:13 UTC, pikurasa requested changes
I'm asking for a few more changes before merging, but otherwise good progress.

Thanks!

2025-01-04 21:13 UTC, pikurasa commented on _posts/2024-12-25-Reflections-as-Parents-and-Teachers-Sugar-at-home-and-in-their-classroom.md
> +title: "Reflections-as-Parents-and-Teachers-Sugar-at-home-and-in-their-classroom"
The title should be the same as the title is in the article.

Also dashes are unnecessary. They render in the HTML, which is not what we want.

![Screenshot from 2025-01-04 16-09-39](https://github.com/user-attachments/assets/9a8d6097-110e-4a89-a92f-ec6fe272d8a4)

2025-01-04 21:13 UTC, pikurasa commented on _posts/2024-9-13-Writing-new-Activities-and-sharing-sugar-with-youth.md
> +title: "Writing-new-Activities-and-sharing-sugar-with-youthclassroom"
Please also correct this title in the manner requested for the other article.

2025-01-04 21:13 UTC, pikurasa commented on _posts/2024-12-25-Reflections-as-Parents-and-Teachers-Sugar-at-home-and-in-their-classroom.md
> +<img src="/assets/stories/students2.jpg" alt="Kai Again <3" class="img-fluid" width="100%"/>
Are you able to alternate where the image appears on the page? (left then right then left etc.)

There's no reason they need to fill the entire width. They do so on Medium because that's the only option that they give us.

2025-01-05 06:25 UTC, MostlyKIGuess commented on _posts/2024-12-25-Reflections-as-Parents-and-Teachers-Sugar-at-home-and-in-their-classroom.md
> +<img src="/assets/stories/students2.jpg" alt="Kai Again <3" class="img-fluid" width="100%"/>
![image](https://github.com/user-attachments/assets/940b2dab-2f6c-4274-8e33-7ddd0047dc41)
- Added changes like this , I am not sure what you mean here. I will be waiting for your confirmation on what exactly is to be done.

2025-01-05 12:26 UTC, MostlyKIGuess commented on _posts/2024-12-25-Reflections-as-Parents-and-Teachers-Sugar-at-home-and-in-their-classroom.md
> +<img src="/assets/stories/students2.jpg" alt="Kai Again <3" class="img-fluid" width="100%"/>
Should be resolved now.

2025-01-09 04:59 UTC, MostlyKIGuess commented
> I'm asking for a few more changes before merging, but otherwise good progress.
> 
> Thanks!

Are there more changes to be made now?

2025-01-09 07:39 UTC, quozl commented on event.html
> +                    <i class="display:block;" >By {{ page.author | default: "Sugar Community Member" }}</i>
Checked again, still a blank before tag close.  Don't make changes you don't need to make?

2025-01-09 11:55 UTC, MostlyKIGuess commented on press.html
> +                    <i class="display:block;" >By {{ post.author | default: "Sugar Community Member" }}</i>
I have resolved this from everywhere now, I am sorry I forgot about it

2025-01-09 20:08 UTC, quozl approved these changes
@pikurasa, your turn.

2025-01-10 16:34 UTC, merged