Add Navigation Links to "Answers to Few Questions" Section
sugarlabs/www pull request #624
Opened 2024-12-30 12:18 UTC by vidipsingh

This pull request enhances the project documentation by adding direct links to the "Answers to few questions" section in the README. The goal is to improve navigation and accessibility, allowing users to easily find answers to common questions and follow necessary steps.

### Changes Made:
- Added clickable links that navigate directly to the "Answers to few questions" section in the README.
- Improved the overall structure and readability of the documentation to provide a more user-friendly experience.

### How to Test:
1. Open the README file.
2. Verify that the new links correctly take you to the "Answers to few questions" section.
3. Ensure that the links function as expected and provide a smoother navigation flow.

### Additional Notes:
This update enhances the documentation by offering quick access to frequently asked questions, helping users find relevant information faster and improving the overall usability of the project’s documentation.

2024-12-30 14:46 UTC, saumyashahi requested changes
The commit message is too lengthy, you should go through this https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits and change the commit accordingly.

2024-12-31 08:57 UTC, quozl commented
You've misunderstood the issue, as it was vague and hadn't reached a clear consensus.  I've summarised the consensus and updated the issue.  Please adjust your change accordingly.

2024-12-31 21:04 UTC, quozl commented
Thanks for your updates.

* [ ] please use GitHub Markdown Anchor Links without the full URL, e.g. `[text](#link-to-heading)`, see https://gist.github.com/rachelhyman/b1f109155c9dafffe618 for an example.

2025-01-10 19:35 UTC, vidipsingh commented
> Thanks for your updates.
> 
> * [ ]  please use GitHub Markdown Anchor Links without the full URL, e.g. `[text](#link-to-heading)`, see https://gist.github.com/rachelhyman/b1f109155c9dafffe618 for an example.

Hi @quozl,
I have updated the commit message to use GitHub Markdown Anchor Links in the specified format, as requested. 
Please let me know if you need any further changes or have any feedback!

2025-01-10 23:01 UTC, quozl commented
Thanks.  Reviewed.  Approve the change.  Don't approve the commit messages; you haven't done what @saumyashahi asked.  I shall rewrite rather than get you to do it, but please in future rewrite your commits or rebase rather than add merge commits.

2025-01-10 23:11 UTC, quozl commented
You also missed an "a" which I've added.  Merged by hand.  See 75b2a0d.

2025-01-10 23:11 UTC, closed without merging